services:
  nginx:
    image: nginx
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    depends_on:
      - app
      - server
    container_name: reverse-proxy
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - mongodata:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
  redis:
    image: redis
    restart: always
    command: [ "redis-server", "--appendonly", "yes" ]
    ports:
      - 6379:6379
    volumes:
      - redisdata:/data
  server:
    image: todo-backend-dev
    depends_on:
      - redis
      - mongo
    volumes:
      - ./todo-backend:/usr/src/app
    container_name: todo-backend-dev
    build:
      context: ./todo-backend
      dockerfile: dev.Dockerfile
    environment:
      - REDIS_URL=redis://redis
      - MONGO_URL=mongodb://the_username:the_password@mongo:27017/the_database
  app:
    image: todo-frontend-dev
    build:
      context: ./todo-frontend
      dockerfile: dev.Dockerfile
    volumes:
      - ./todo-frontend:/usr/src/app
    container_name: todo-frontend-dev
    environment:
      - VITE_BACKEND_URL=http://localhost:8080/api/
volumes:
  mongodata:
  redisdata:
