services:
  mongo:
    image: mongo
    volumes:
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - mongodata:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
  redis:
    image: redis
    restart: always
    command: [ "redis-server", "--appendonly", "yes" ]
    volumes:
      - redisdata:/data
  server:
    image: todo-backend
    depends_on:
      - redis
      - mongo
    volumes:
      - ./todo-backend:/usr/src/app
    container_name: todo-backend-dev
    build:
      context: ./todo-backend
    environment:
      - REDIS_URL=redis://redis
      - MONGO_URL=mongodb://the_username:the_password@mongo:27017/the_database
  nginx:
    image: todo-frontend
    build:
      context: ./todo-frontend
      args:
        - VITE_BACKEND_URL=http://localhost:8080/api/
    volumes:
      - ./todo-frontend:/usr/src/app
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    container_name: reverse-proxy
    ports:
      - 8080:80
    depends_on:
      - server
volumes:
  mongodata:
  redisdata:
