services:
  mongo:
    image: mongo
    ports:
    - 27017:27017
    volumes:
     - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
     - mongodata:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
  redis:
    image: redis
    restart: always
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - 6379:6379
    volumes:
      - redisdata:/data
  server:
    image: todo-backend-dev
    depends_on:
      - redis
      - mongo
    volumes:
      - .:/usr/src/app
    ports:
      - 3000:3000
    container_name: todo-backend-dev
    environment:
      - REDIS_URL=redis://redis
      - MONGO_URL=mongodb://the_username:the_password@mongo:27017/the_database
    
volumes:
  mongodata:
  redisdata: